spring:
  profiles:
    active:
    -dev

---

spring:
  profiles:
    active: dev
  application:
    name: microservice-config-qicheng-dev

---

spring:
  profiles:
    active: test
  application:
    name: microservice-config-qicheng-test